encoding: UTF-8
serial:
-
  name : com1
  dev  : /dev/ttyAMA0
  baudrate: 460800
  port : 1101
  mode : tcp
-
  name : com2
  dev  : /dev/ttyAMA1
  baudrate: 460800
  port : 1102
  mode : tcp
-
  name : com3
  dev  : /dev/ttyAMA2
  baudrate: 115200
  port : 1103
  mode : tcp
-
  name : com2
  dev  : /dev/ttyAMA3
  baudrate: 115200
  port : 1104
  mode : udp